channels:
- conda-forge
dependencies:
- python=3.11.14
- pip<=26.0.1
- pip:
  - mlflow==2.11.0
  - cloudpickle==3.1.2
  - numpy==1.26.0
  - packaging==23.2
  - pyyaml==6.0.3
  - scikit-learn==1.4.0
  - scipy==1.16.3
name: mlflow-env
